import os
from g2pk import G2p

# G2P 객체 생성
g2p = G2p()

# 상대 경로로 저장할 디렉토리 경로 설정
base_dir = os.path.abspath("./DiscordTTSBotRaccoon/TTS-0.13.1/DataSet")
wav_directory = os.path.abspath(os.path.join(base_dir, "wavs"))
metadata_path = os.path.join(base_dir, "metadata.csv")

# 구간 설정 및 텍스트 정의
segments = [
    {"wav_file": os.path.join(wav_directory, "segment_175.wav"), "text": "촌장님."},
    {"wav_file": os.path.join(wav_directory, "segment_176.wav"), "text": "흐응... 코미는 사료면 충분해."},
    {"wav_file": os.path.join(wav_directory, "segment_177.wav"), "text": "그러니까 창고 개방! 사료 떨이 이벤트 같은 거나 더 해줘."},
    {"wav_file": os.path.join(wav_directory, "segment_178.wav"), "text": "아니야, 됐어."},
    {"wav_file": os.path.join(wav_directory, "segment_179.wav"), "text": "마녀랑 요정 여왕은 왜 싸운 거야?"},
    {"wav_file": os.path.join(wav_directory, "segment_180.wav"), "text": "코미는 왜 싸우는지 알아."},
    {"wav_file": os.path.join(wav_directory, "segment_181.wav"), "text": "편견 때문이야."},
    {"wav_file": os.path.join(wav_directory, "segment_182.wav"), "text": "요정이랑 마녀는 모양이 달라."},
    {"wav_file": os.path.join(wav_directory, "segment_183.wav"), "text": "그래서 서로를 이해 못하는 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_184.wav"), "text": "책에서 읽었어. 코미도 자세히는 몰라. 그냥 그렇대."},
    {"wav_file": os.path.join(wav_directory, "segment_185.wav"), "text": "아무튼, 촌장님은 다들 친하게 지냈으면 하는 거야?"},
    {"wav_file": os.path.join(wav_directory, "segment_186.wav"), "text": "흐음... 코미한테 좋은 생각이 있어!"},
    {"wav_file": os.path.join(wav_directory, "segment_187.wav"), "text": "다들 우리 마을에 초대하자!"},
    {"wav_file": os.path.join(wav_directory, "segment_188.wav"), "text": "초대해서 같이 놀 놀이터를 만들면 다들 재미있게 놀면서 친해질 거야!"},
    {"wav_file": os.path.join(wav_directory, "segment_189.wav"), "text": "아니, 아니. 음... 놀이터... 아주 큰 놀이터... 훌륭한 대화 수단..."},
    {"wav_file": os.path.join(wav_directory, "segment_190.wav"), "text": "호수에 놀이터를 만들면 다들 재미있게 놀 수 있어!"},
    {"wav_file": os.path.join(wav_directory, "segment_191.wav"), "text": "응! 코미 똑똑해! 책에서 어떻게 하는지 다 읽었어!"},
    {"wav_file": os.path.join(wav_directory, "segment_192.wav"), "text": "코미에게 맡겨줘! 히히!"},
    {"wav_file": os.path.join(wav_directory, "segment_193.wav"), "text": "코미는 세상에서 제일가는 놀이터 주인이 될거야! 헤헤!"},
    {"wav_file": os.path.join(wav_directory, "segment_194.wav"), "text": "여왕님?"},
    {"wav_file": os.path.join(wav_directory, "segment_195.wav"), "text": "여기 근처까진 코미의 활동 영역이야."},
    {"wav_file": os.path.join(wav_directory, "segment_196.wav"), "text": "그 질문은 코미가 하는게 자연스러운 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_197.wav"), "text": "여왕님 여기서 뭐해?"},
    {"wav_file": os.path.join(wav_directory, "segment_198.wav"), "text": "으흠? 여왕님 또 도망친 거지? 일하기 싫어서?"},
    {"wav_file": os.path.join(wav_directory, "segment_199.wav"), "text": "괜찮아! 퍼리 비이치는 그냥 아무 생각 안하고 놀면 돼!"},
    {"wav_file": os.path.join(wav_directory, "segment_200.wav"), "text": "자자, 이렇게 코미가 부채질도 해주고 수영복도 대여해줄게! 그냥 바닥에 누워!"},
    {"wav_file": os.path.join(wav_directory, "segment_201.wav"), "text": "에이 부끄러하지 않아도 돼. 그냥 편하게 쉬어!"},
    {"wav_file": os.path.join(wav_directory, "segment_202.wav"), "text": "지금은 진흙이지만, 코미가 열심히 일해서 모래사장으로 바꿀 거야!"},
    {"wav_file": os.path.join(wav_directory, "segment_203.wav"), "text": "자, 코미가 만든 코미 주스도 먹어봐!"},
    {"wav_file": os.path.join(wav_directory, "segment_204.wav"), "text": "크흠... 여왕님."},
    {"wav_file": os.path.join(wav_directory, "segment_205.wav"), "text": "이제 돈 줘."},
    {"wav_file": os.path.join(wav_directory, "segment_206.wav"), "text": "코미가 최고의 서비스를 제공했으니까, 여왕님이 돈을 내야 해."},
    {"wav_file": os.path.join(wav_directory, "segment_207.wav"), "text": "빨리 줘. 여왕이니까 로열티 얹어서 내야 해."},
    {"wav_file": os.path.join(wav_directory, "segment_208.wav"), "text": "흐음... 여왕님... 돈 없어?"},
    {"wav_file": os.path.join(wav_directory, "segment_209.wav"), "text": "여왕님... 그럼 몸으로 갚아."},
    {"wav_file": os.path.join(wav_directory, "segment_210.wav"), "text": "받아줘야지. 코미는... 세상에서 제일가는... 놀이터 주인이 될 거야. 우히히~"},
    {"wav_file": os.path.join(wav_directory, "segment_211.wav"), "text": "평범한 액체로는 절대 지울 수 없는 만능 펜이야."},
    {"wav_file": os.path.join(wav_directory, "segment_212.wav"), "text": "코미가 여왕님을 완벽한 노동자의 모습으로 변신시켜줄게."},
    {"wav_file": os.path.join(wav_directory, "segment_213.wav"), "text": "김씨."},
    {"wav_file": os.path.join(wav_directory, "segment_214.wav"), "text": "오늘 해질 때까지는 여기부터 저기까지 모래로 바꿔야 해? 알겠지?"},
    {"wav_file": os.path.join(wav_directory, "segment_215.wav"), "text": "코미는 진짜를 원해. 마법 같은 쉬운 힘으로는 진짜를 쟁취할 수 없어."},
    {"wav_file": os.path.join(wav_directory, "segment_216.wav"), "text": "김씨, 아직도 정신을 못 차렸어?"},
    {"wav_file": os.path.join(wav_directory, "segment_217.wav"), "text": "임무를 완수하지 못한다면, 평생 그 낙서를 얼굴에 달고 살아야 한다고?"},
    {"wav_file": os.path.join(wav_directory, "segment_218.wav"), "text": "허?! 단체... 손님?!"},
    {"wav_file": os.path.join(wav_directory, "segment_219.wav"), "text": "마고!"},
    {"wav_file": os.path.join(wav_directory, "segment_220.wav"), "text": "어- 어서 오세요! 퍼리 비이치 리조토입니다앗!"},
    {"wav_file": os.path.join(wav_directory, "segment_221.wav"), "text": "응! 코미가 여기 주인이야! 촌장한테 듣고 왔구나!"},
    {"wav_file": os.path.join(wav_directory, "segment_222.wav"), "text": "추천인 추천 받고 오셨으면 더 좋은 서비스를 제공해 줄 수 있어!"},
    {"wav_file": os.path.join(wav_directory, "segment_223.wav"), "text": "아직 5평밖에 안 되지만... 저기 해변에 누워서 휴식할 수 있어!"},
    {"wav_file": os.path.join(wav_directory, "segment_224.wav"), "text": "부채질 10분이랑 코미 주스도 줄게!"},
    {"wav_file": os.path.join(wav_directory, "segment_225.wav"), "text": "이상해? 코미 이름이 이상하다는 거야?"},
    {"wav_file": os.path.join(wav_directory, "segment_226.wav"), "text": "아냐야. 에르핀 아니라 김씨야!"},
    {"wav_file": os.path.join(wav_directory, "segment_227.wav"), "text": "코미랑 놀이터 만들고 있는 착한 노예... 아니, 친구야!"},
    {"wav_file": os.path.join(wav_directory, "segment_228.wav"), "text": "응! 모래성도 쌓고... 놀이터에서 하는 그런 거!"},
    {"wav_file": os.path.join(wav_directory, "segment_229.wav"), "text": "마고도 같이 놀고 싶지 않아?"},
    {"wav_file": os.path.join(wav_directory, "segment_230.wav"), "text": "아... 여기 자주 왔었어?"},
    {"wav_file": os.path.join(wav_directory, "segment_231.wav"), "text": "마고... 그럼 그동안 계속 무전취식한 거야?"},
    {"wav_file": os.path.join(wav_directory, "segment_232.wav"), "text": "퍼리 비이치는 이제 이용료 내야 해."},
    {"wav_file": os.path.join(wav_directory, "segment_233.wav"), "text": "그런데 마고는 이용료 생기기 전부터 계속 여기서 놀았으니까..."},
    {"wav_file": os.path.join(wav_directory, "segment_234.wav"), "text": "이용료가 엄청 밀려있는 거야. 그러니까 밀린 거 다 내야 해."},
    {"wav_file": os.path.join(wav_directory, "segment_235.wav"), "text": "코미는 돈으로 장난 안 해."},
    {"wav_file": os.path.join(wav_directory, "segment_236.wav"), "text": "물... 비가 내리면 다시 차니까 무한 자원이야. 돈 낼 필요가 없어."},
    {"wav_file": os.path.join(wav_directory, "segment_237.wav"), "text": "호수는 장소니까 없어지면 차원이 붕괴할 거야. 사고팔 수 있어."},
    {"wav_file": os.path.join(wav_directory, "segment_238.wav"), "text": "빵집 살면서 매달 이용료를 내는 요정처럼."},
    {"wav_file": os.path.join(wav_directory, "segment_239.wav"), "text": "그리고 퍼리 비이치는 사용할 때마다 돈을 내는 구조로 되어 있어."},
    {"wav_file": os.path.join(wav_directory, "segment_240.wav"), "text": "그러니까 마고는 밀린 이용료 다 합쳐서 내야 해."},
    {"wav_file": os.path.join(wav_directory, "segment_241.wav"), "text": "흐으음... 마고랑... 마고 동물 친구들이랑... 자주 왔을 테니까... 다 합치면..."},
    {"wav_file": os.path.join(wav_directory, "segment_242.wav"), "text": "대충 이만 코미 코인이야."},
    {"wav_file": os.path.join(wav_directory, "segment_243.wav"), "text": "퍼리 비이치 쿠폰 이름이야!"},
    {"wav_file": os.path.join(wav_directory, "segment_244.wav"), "text": "코미도 잘 몰라."},
    {"wav_file": os.path.join(wav_directory, "segment_245.wav"), "text": "흐응... 새 손님을 데려왔네?"},
    {"wav_file": os.path.join(wav_directory, "segment_246.wav"), "text": "그냥 빨리 내라는 거 내란 말이야!"},
    {"wav_file": os.path.join(wav_directory, "segment_247.wav"), "text": "잠깐! 마고, 너에게 제안을 하나 하지."},
    {"wav_file": os.path.join(wav_directory, "segment_248.wav"), "text": "코미 코인을 지불하는 대신, 내 일을 돕게 해줄게."},
    {"wav_file": os.path.join(wav_directory, "segment_249.wav"), "text": "마고와 함께라면... 퍼리 비이치를 예스애니멀존으로 만들 수 있어!"},
    {"wav_file": os.path.join(wav_directory, "segment_250.wav"), "text": "잠깐만 고생하면, 동물 친구들과 놀러올 수 있는 멋진 리조토를 얻을 수 있다구?"},
    {"wav_file": os.path.join(wav_directory, "segment_251.wav"), "text": "마고. 이건 오직 너만 할 수 있는 일이야."},
    {"wav_file": os.path.join(wav_directory, "segment_252.wav"), "text": "동물 친구들에게도 호수 조망권을 보장해 줘야 하지 않겠어?"},
    {"wav_file": os.path.join(wav_directory, "segment_253.wav"), "text": "만약 제안을 거절한다면... 호수 근처의 산책로를 모두 통제하겠다!"},
    {"wav_file": os.path.join(wav_directory, "segment_254.wav"), "text": "후후... 모두 코미의 계획대로 순조롭게 진행되고 있어."},
    {"wav_file": os.path.join(wav_directory, "segment_255.wav"), "text": "이제부터 넌 수질 관리를 하게 될 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_256.wav"), "text": "내일까지 호수를 소금물로 바꿔놔."},
    {"wav_file": os.path.join(wav_directory, "segment_257.wav"), "text": "하지만 호수가 짠물이 아니면 비이치가 아니잖아!"},
    {"wav_file": os.path.join(wav_directory, "segment_258.wav"), "text": "마고. 동물 친구들을 위해 내 말대로 일하기로 했잖아!"},
    {"wav_file": os.path.join(wav_directory, "segment_259.wav"), "text": "흐으음... 그럼 마고 대신 김씨의 손을 이용하면 되겠네. 어이 김씨!"},
    {"wav_file": os.path.join(wav_directory, "segment_260.wav"), "text": "호수에 소금 좀 풀어."},
    {"wav_file": os.path.join(wav_directory, "segment_261.wav"), "text": "잔말 말고 시키는 대로 해!"},
    {"wav_file": os.path.join(wav_directory, "segment_262.wav"), "text": "소금은 저기 있어. 오늘을 위해 대량 구매 해뒀거든."},
    {"wav_file": os.path.join(wav_directory, "segment_263.wav"), "text": "아, 김씨. 그전에 우선 마고에게 하던 일을 인수인계해 줘."},
    {"wav_file": os.path.join(wav_directory, "segment_264.wav"), "text": "하~ 김씨, 손 많이 가네."},
    {"wav_file": os.path.join(wav_directory, "segment_265.wav"), "text": "마고에게 니가 어떤 일을 하고 있었는지, 어떻게 하면 되는지 알려주라구!"},
    {"wav_file": os.path.join(wav_directory, "segment_266.wav"), "text": "그럼 난 잠깐 중요한 미팅을 하고 올게."},
    {"wav_file": os.path.join(wav_directory, "segment_267.wav"), "text": "마고, 김씨에게 일 잘 배워두라구."},
    {"wav_file": os.path.join(wav_directory, "segment_268.wav"), "text": "그치만... 호수가 멋진 곳이 되지 않으면, 다른 마을이랑 친해질 수 없다구."},
    {"wav_file": os.path.join(wav_directory, "segment_269.wav"), "text": "촌장이 그랬어. 코미만 믿을 테니까 호수를 멋지게 바꾸라고."},
    {"wav_file": os.path.join(wav_directory, "segment_270.wav"), "text": "하지만 진짠데...? 코미의 논리는 완벽했으니까 말이야."},
    {"wav_file": os.path.join(wav_directory, "segment_271.wav"), "text": "하아~ 코미는 좋은 일 하는건데... 왜 다들 나랑 싸우려고 하는거야...?"},
    {"wav_file": os.path.join(wav_directory, "segment_272.wav"), "text": "자꾸 딴소리하면, 퍼리 비이치를 노애니멀존으로 만들어 버린다?"},
    {"wav_file": os.path.join(wav_directory, "segment_273.wav"), "text": "허어... 아까부터 살짝 거슬렸는데... 마고 너... 말이 짧아?"},
    {"wav_file": os.path.join(wav_directory, "segment_274.wav"), "text": "난 사장이고, 넌 노동자라구?"},
    {"wav_file": os.path.join(wav_directory, "segment_275.wav"), "text": "흐으음... 퍼리 비이치의 비약적인 발전을 위해서는, 무식하게 센 힘이 더 필요해."},
    {"wav_file": os.path.join(wav_directory, "segment_276.wav"), "text": "흐흐 마침 눈 앞에 지나가는군. 역시 코미는 운이 좋단 말이야."},
    {"wav_file": os.path.join(wav_directory, "segment_277.wav"), "text": "베니! 베니!"},
    {"wav_file": os.path.join(wav_directory, "segment_278.wav"), "text": "베니, 코미랑 놀이터 같이 만들지 않을래?"},
    {"wav_file": os.path.join(wav_directory, "segment_279.wav"), "text": "촌장이 코미보고 호수를 놀이터로 바꿔놓으랬어!"},
    {"wav_file": os.path.join(wav_directory, "segment_280.wav"), "text": "코미랑 열심히 일하면 빵도 주고, 꿀도 주고, 코미 주스도 줄게!"},
    {"wav_file": os.path.join(wav_directory, "segment_281.wav"), "text": "응! 베니가 먹고 싶은 만큼 다 줄 수 있어."},
    {"wav_file": os.path.join(wav_directory, "segment_282.wav"), "text": "퍼리 비이치는 코미 코인만 있으면 뭐든지 마음대로 할 수 있어!"},
    {"wav_file": os.path.join(wav_directory, "segment_283.wav"), "text": "코미는 촌장이 시킨 대로 열심히 일하는 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_284.wav"), "text": "코미 옆에 서있으면 돼! 베니가 내 오른쪽 어깨가 되는 거야!"},
    {"wav_file": os.path.join(wav_directory, "segment_285.wav"), "text": "베니, 언제까지 오른팔에만 머물러 있을 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_286.wav"), "text": "더 높은 감투가 탐나지 않아?"},
    {"wav_file": os.path.join(wav_directory, "segment_287.wav"), "text": "생각해 봐 베니. 팔과 어깨, 어느 것이 더 위에 있지?"},
    {"wav_file": os.path.join(wav_directory, "segment_288.wav"), "text": "후훗... 지금이라도 깨달았으면 됐어. 모르는 건 부끄러운 게 아니니까."},
    {"wav_file": os.path.join(wav_directory, "segment_289.wav"), "text": "응. 코미 옆에만 있어."},
    {"wav_file": os.path.join(wav_directory, "segment_290.wav"), "text": "베니, 지금 협상의 기술을 사용하고 있는 거야?"},
    {"wav_file": os.path.join(wav_directory, "segment_291.wav"), "text": "좋아. 일당도 줄게. 하루 8시간 일하고 일당은 오백코인이야."},
    {"wav_file": os.path.join(wav_directory, "segment_292.wav"), "text": "응. 어때? 이렇게 파격적인 조건은 두 번 다신 없을 거라구?"},
    {"wav_file": os.path.join(wav_directory, "segment_293.wav"), "text": "넌 정말 행운아야, 베니."},
    {"wav_file": os.path.join(wav_directory, "segment_294.wav"), "text": "루포가 잘 알고 있네. 엄청엄청 좋은 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_295.wav"), "text": "그래, 그래. 그건 걱정하지 말라구."},
    {"wav_file": os.path.join(wav_directory, "segment_296.wav"), "text": "거기 마녀. 에르핀을 찾고 있나?"},
    {"wav_file": os.path.join(wav_directory, "segment_297.wav"), "text": "코미는 깔끔한 걸 좋아하니까, 거두절미하고 본론만 이야기하겠어."},
    {"wav_file": os.path.join(wav_directory, "segment_298.wav"), "text": "코미와 같이 일하면, 에르핀이 어디에 숨어있는지 알려줄게."},
    {"wav_file": os.path.join(wav_directory, "segment_299.wav"), "text": "흐으음... 그렇게 나온다 이거지..."},
    {"wav_file": os.path.join(wav_directory, "segment_300.wav"), "text": "너, 아까 보니까 김씨와 아는 사이인 것 같던데."},
    {"wav_file": os.path.join(wav_directory, "segment_301.wav"), "text": "이봐, 김씨! 이리 와!"},
    {"wav_file": os.path.join(wav_directory, "segment_302.wav"), "text": "잘 들어, 벨벳... 코미가 시키는 대로 하지 않으면..."},
    {"wav_file": os.path.join(wav_directory, "segment_303.wav"), "text": "삽질 노동자 김씨의 식사 메뉴는 평생 코미 주스가 될 것이다."},
    {"wav_file": os.path.join(wav_directory, "segment_304.wav"), "text": "자, 어떻게 할 거지?"},
    {"wav_file": os.path.join(wav_directory, "segment_305.wav"), "text": "코미 주스도 모르다니, 정말 트렌드에 빠삭하지 못하군."},
    {"wav_file": os.path.join(wav_directory, "segment_306.wav"), "text": "여기서 코미 주스 레시피를 최초 공개하게 될 줄은 몰랐지만, 어쩔 수 없지."},
    {"wav_file": os.path.join(wav_directory, "segment_307.wav"), "text": "자, 완성했어."},
    {"wav_file": os.path.join(wav_directory, "segment_308.wav"), "text": "자, 김씨. 벨벳이 일을 하지 않으면 넌 이 코미 주스를 코로 마셔야 한다."},
    {"wav_file": os.path.join(wav_directory, "segment_309.wav"), "text": "흐음... 역시 세상 사는데 쉬운 일 하나 없네."},
    {"wav_file": os.path.join(wav_directory, "segment_310.wav"), "text": "자, 그럼... 네가 거절할 수 없을 정도로 파격적인 조건을 제안하겠다."},
    {"wav_file": os.path.join(wav_directory, "segment_311.wav"), "text": "너, 돈은 좀 있어?"},
    {"wav_file": os.path.join(wav_directory, "segment_312.wav"), "text": "왕국을 세우려면, 돈이 얼마나 많이 들어가는지 알고는 있지?"},
    {"wav_file": os.path.join(wav_directory, "segment_313.wav"), "text": "여왕의 자본력은 곧 공권력으로 직결된다고 했어."},
    {"wav_file": os.path.join(wav_directory, "segment_314.wav"), "text": "요정 왕국만 봐도 알 수 있는 사실이잖아?"},
    {"wav_file": os.path.join(wav_directory, "segment_315.wav"), "text": "하루 네 시간, 일당은 천코인."},
    {"wav_file": os.path.join(wav_directory, "segment_316.wav"), "text": "응? 어디서 환청이 들리나."},
    {"wav_file": os.path.join(wav_directory, "segment_317.wav"), "text": "코미 코인이야. 골드보다 훨씬 높은 가치를 자랑하지."},
    {"wav_file": os.path.join(wav_directory, "segment_318.wav"), "text": "좋은 생각이야. 퍼리 비이치에 온 걸 환영해."},
    {"wav_file": os.path.join(wav_directory, "segment_319.wav"), "text": "넌 이제부터 퍼리 비이치의 부사장이야."},
    {"wav_file": os.path.join(wav_directory, "segment_320.wav"), "text": "아주 좋군."},
    {"wav_file": os.path.join(wav_directory, "segment_321.wav"), "text": "코미...? 말이 짧은 것 같은데?"},
    {"wav_file": os.path.join(wav_directory, "segment_322.wav"), "text": "베니, 날 사장이라 부르라고 했을 텐데?"},
    {"wav_file": os.path.join(wav_directory, "segment_323.wav"), "text": "이번이 벌써 두 번째야."},
    {"wav_file": os.path.join(wav_directory, "segment_324.wav"), "text": "아쉽지만, 난 한 번은 봐줘도 두 번은 봐주지 않아."},
    {"wav_file": os.path.join(wav_directory, "segment_325.wav"), "text": "친구 사이여도 공과 사는 철저하게 구분해야지."},
    {"wav_file": os.path.join(wav_directory, "segment_326.wav"), "text": "베니는 인형 알바형에 처한다."},
    {"wav_file": os.path.join(wav_directory, "segment_327.wav"), "text": "일단 시키는 대로 해! 코미 코인을 받고 싶지 않은 거야?"},
    {"wav_file": os.path.join(wav_directory, "segment_328.wav"), "text": "마을의 이익을 위해서 내 한 몸 바쳐서 일했지만..."},
    {"wav_file": os.path.join(wav_directory, "segment_329.wav"), "text": "아무도 날 인정해 주지 않았어."},
    {"wav_file": os.path.join(wav_directory, "segment_330.wav"), "text": "오히려 자신들의 권리와 이익만 챙기기 위해 목소리를 높이고 있다고!"},
    {"wav_file": os.path.join(wav_directory, "segment_331.wav"), "text": "코미는... 더 이상 착하지 않아!"},
    {"wav_file": os.path.join(wav_directory, "segment_332.wav"), "text": "퍼리 비이치 사업은 이제부터 블랙 사업이야."},
    {"wav_file": os.path.join(wav_directory, "segment_333.wav"), "text": "흥 그건 배부른 녀석들이나 하는 소리지."},
    {"wav_file": os.path.join(wav_directory, "segment_334.wav"), "text": "며칠 굶어보면 그런 말 못 할 걸?"},
    {"wav_file": os.path.join(wav_directory, "segment_335.wav"), "text": "베니에게 인형 알바형을 내렸는데 베니가 말을 듣지 않아."},
    {"wav_file": os.path.join(wav_directory, "segment_336.wav"), "text": "부사장, 왔군. 노동자 관리는 수월하게 진행되고 있나?"},
    {"wav_file": os.path.join(wav_directory, "segment_337.wav"), "text": "좋아. 벨벳 부사장처럼 유능한 간부가 생겨서 기뻐."},
    {"wav_file": os.path.join(wav_directory, "segment_338.wav"), "text": "베니, 안 나가고 뭐 하고 있어?"},
    {"wav_file": os.path.join(wav_directory, "segment_339.wav"), "text": "부사장과 중요한 이야기를 나눠야 하니까, 어서 나가 줘."},
    {"wav_file": os.path.join(wav_directory, "segment_340.wav"), "text": "공사도 거의 끝나가니까, 다음 계획을 브리핑할까 해."},
    {"wav_file": os.path.join(wav_directory, "segment_341.wav"), "text": "엘리아스 숲에... 더 많은 해변을 만들 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_342.wav"), "text": "숲 한복판에 강을 뜷을 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_343.wav"), "text": "퍼리 비이치 리조토에 불나방처럼 손님들이 몰려오면..."},
    {"wav_file": os.path.join(wav_directory, "segment_344.wav"), "text": "나를 위해 일해줄 노동자들이 더 많아지겠지."},
    {"wav_file": os.path.join(wav_directory, "segment_345.wav"), "text": "엘리아스 바캉스 대혁명... 이젠 그게 내 목표다."},
    {"wav_file": os.path.join(wav_directory, "segment_346.wav"), "text": "엘리아스 전체를 바캉스 천국으로 만들겠어!"},
    {"wav_file": os.path.join(wav_directory, "segment_347.wav"), "text": "사장."},
    {"wav_file": os.path.join(wav_directory, "segment_348.wav"), "text": "코미 사장이라고."},
    {"wav_file": os.path.join(wav_directory, "segment_349.wav"), "text": "돌아왔군, 디아나 촌장."},
    {"wav_file": os.path.join(wav_directory, "segment_350.wav"), "text": "뒤에 따라온 녀석들은... 아아, 그래. 노동조합이라고 하던가."},
    {"wav_file": os.path.join(wav_directory, "segment_351.wav"), "text": "촌장도 나와 싸우려는 건가?"},
    {"wav_file": os.path.join(wav_directory, "segment_352.wav"), "text": "사실이라면 뭐 어쩔 거지?"},
    {"wav_file": os.path.join(wav_directory, "segment_353.wav"), "text": "코미는... 그러려고 했어."},
    {"wav_file": os.path.join(wav_directory, "segment_354.wav"), "text": "하지만 모두가 내 말을 듣지 않았어."},
    {"wav_file": os.path.join(wav_directory, "segment_355.wav"), "text": "모두가 날 이렇게 만든 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_356.wav"), "text": "흐음... 아직도 눈치채지 못한 건가."},
    {"wav_file": os.path.join(wav_directory, "segment_357.wav"), "text": "그 펜은 사실... 평범한 수성펜이었다고."},
    {"wav_file": os.path.join(wav_directory, "segment_358.wav"), "text": "세상이 코미를 버리겠다면, 코미가 세상을 버리겠어!"},
    {"wav_file": os.path.join(wav_directory, "segment_359.wav"), "text": "흥, 싫은데?"},
    {"wav_file": os.path.join(wav_directory, "segment_360.wav"), "text": "이익 모두 미워! 결국 촌장도 내 말 안 듣잖아!"},
    {"wav_file": os.path.join(wav_directory, "segment_361.wav"), "text": "코미는 잘못 없어! 다들 코미의 퍼리 비이치를 소중하게 여기지 않아!"},
    {"wav_file": os.path.join(wav_directory, "segment_362.wav"), "text": "코미는... 코미는 그저 세상에서 제일가는 놀이터 주인이 되고 싶었을 뿐이야!"},
    {"wav_file": os.path.join(wav_directory, "segment_363.wav"), "text": "이잉 코미는 억울해! 억울하다고!"},
    {"wav_file": os.path.join(wav_directory, "segment_364.wav"), "text": "우씨이..."},
    {"wav_file": os.path.join(wav_directory, "segment_365.wav"), "text": "코미는 사과하지 않..."},
    {"wav_file": os.path.join(wav_directory, "segment_366.wav"), "text": "키야악! 아프잖아, 촌장님!"},
    {"wav_file": os.path.join(wav_directory, "segment_367.wav"), "text": "흑... 흐윽..."},
    {"wav_file": os.path.join(wav_directory, "segment_368.wav"), "text": "꿈을 꿨어요... 달콤한 꿈을..."},
    {"wav_file": os.path.join(wav_directory, "segment_369.wav"), "text": "크이익! 때린 곳을 또 때리는 건 불법이야!"},
    {"wav_file": os.path.join(wav_directory, "segment_370.wav"), "text": "다 끝났어, 부사장. 코미의 꿈은 한순간이었던 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_371.wav"), "text": "그래, 부사장. 여기 코인 다 가져가."},
    {"wav_file": os.path.join(wav_directory, "segment_372.wav"), "text": "너만은 날 믿고 따라줬으니까, 말했던 것보다 더 넣었어."},
    {"wav_file": os.path.join(wav_directory, "segment_373.wav"), "text": "못 바꾸는데? 그 코인은 퍼리 비이치에서만 자유롭게 사용할 수 있는 거야."},
    {"wav_file": os.path.join(wav_directory, "segment_374.wav"), "text": "..흥"},
    {"wav_file": os.path.join(wav_directory, "segment_375.wav"), "text": "그치만... 그렇게 하는 건 어렵잖아."},
    {"wav_file": os.path.join(wav_directory, "segment_376.wav"), "text": "코미 혼자서는 호수를 이렇게 만들 수는 없잖아."},
    {"wav_file": os.path.join(wav_directory, "segment_377.wav"), "text": "으음... 아니."},
    {"wav_file": os.path.join(wav_directory, "segment_378.wav"), "text": "그렇게 하면 아무도 안 도와줄 것 같아서..."},
    {"wav_file": os.path.join(wav_directory, "segment_379.wav"), "text": "응... 응?"},
    {"wav_file": os.path.join(wav_directory, "segment_380.wav"), "text": "우웅..."},
    {"wav_file": os.path.join(wav_directory, "segment_381.wav"), "text": "저 촌장님. 코미 부탁이 있어."},
    {"wav_file": os.path.join(wav_directory, "segment_382.wav"), "text": "퍼리 비이치를 복구시키기 전에 마지막으로 즐기게 해줘."},
    {"wav_file": os.path.join(wav_directory, "segment_383.wav"), "text": "그동안 고생한 직원들과 함께... 놀고 싶어."},
    {"wav_file": os.path.join(wav_directory, "segment_384.wav"), "text": "응! 알겠어!"},
    {"wav_file": os.path.join(wav_directory, "segment_385.wav"), "text": "코미와 놀고 싶은 자, 당장 수영복으로 갈아 입는다. 실시!"},
    {"wav_file": os.path.join(wav_directory, "segment_386.wav"), "text": "코미의 진정한 바캉스는 이제부터 시작이야!"},
    {"wav_file": os.path.join(wav_directory, "segment_387.wav"), "text": "감히 코미의 영역을 침범하다니, 다들 겁도 없구나!"},
    {"wav_file": os.path.join(wav_directory, "segment_388.wav"), "text": "침입자들 모두 코미의 물대포를 받아랏!"},
    {"wav_file": os.path.join(wav_directory, "segment_389.wav"), "text": "으헤헤. 이거 엄청 재밌잖아?"},
    {"wav_file": os.path.join(wav_directory, "segment_390.wav"), "text": "이렇게 즐거운 물놀이에 음료수가 빠질 수 없지."},
    {"wav_file": os.path.join(wav_directory, "segment_391.wav"), "text": "베니, 당장 뛰어가서 코미 주스 한 잔을 대령하라!"},
    {"wav_file": os.path.join(wav_directory, "segment_392.wav"), "text": "후후, 고급 농담이었어."},
    {"wav_file": os.path.join(wav_directory, "segment_393.wav"), "text": "따지고 보면, 지금 코미가 담겨진 이 호수의 물 전체가 코미 주스거든."},
    {"wav_file": os.path.join(wav_directory, "segment_394.wav"), "text": "그러니까, 오늘은 아무 생각 없이 놀자. 베니."},
    {"wav_file": os.path.join(wav_directory, "segment_395.wav"), "text": "기꺼이 상대해 주지, 김씨!"}
    # 필요한 만큼 구간 추가 가능
]

# Coqui TTS 학습을 위한 metadata.csv 파일에 추가
with open(metadata_path, "a", encoding="utf-8") as metadata_file:
    for segment in segments:
        segment_wav = os.path.abspath(segment["wav_file"])
        
        # 파일 이름에서 확장자 제거
        segment_name = os.path.splitext(segment_wav)[0]
        
        text = segment["text"]
        phoneme_text = g2p(text)  # G2P 변환

        # metadata 파일에 '파일 이름|텍스트|음소 변환 텍스트' 형식으로 추가
        metadata_file.write(f"{segment_name}|{text}|{phoneme_text}\n")

print(f"Metadata 파일에 내용이 추가되었습니다: {metadata_path}")


